// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTS6BSdg7xMcfvcKxDb5oqXJjYyNFvXLM',
    appId: '1:654337446519:web:736b3b5a3637423bd3ec72',
    messagingSenderId: '654337446519',
    projectId: 'rapilead-b41b9',
    authDomain: 'rapilead-b41b9.firebaseapp.com',
    storageBucket: 'rapilead-b41b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjZWcYznVuRxVdIWT_T9eWctpw6MfOxSU',
    appId: '1:654337446519:android:d07666ab0d147c25d3ec72',
    messagingSenderId: '654337446519',
    projectId: 'rapilead-b41b9',
    storageBucket: 'rapilead-b41b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANuITByYBQ03X4bAvqCb10dTj6hGFlnDc',
    appId: '1:654337446519:ios:1e3d5f3cebc032f4d3ec72',
    messagingSenderId: '654337446519',
    projectId: 'rapilead-b41b9',
    storageBucket: 'rapilead-b41b9.firebasestorage.app',
    iosBundleId: 'com.example.rapilead',
  );
}
